apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-p6jn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-p6jn
    app.kubernetes.io/part-of: node-hello
  name: node-express-hello-p6jn
  namespace: bsutter-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-express-hello-p6jn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-express-hello-p6jn
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c16aacba4933aab479d0ada4fbdf126759eabf1309bae3fd66dcc91965fd1988
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
