apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-p6jn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-p6jn
    app.kubernetes.io/part-of: node-hello
  name: node-express-hello-p6jn
  namespace: bsutter-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: node-express-hello-p6jn
    weight: null
status: {}
